### ISSUE TITLE
Support of icingaweb2?

### ISSUE THREAD

**Issue by matrixise** [transitiv/ansible-role-icinga2#5]
Hi,

Thank you for your Ansible role, it's great.

Do you use/have a role for icingaweb2?

Thank you

**Comment by atj** [comment]
Glad you find the role useful :+1:  

We don't currently have or use a separate role for installing Icinga Web 2. If all you need is for the Icinga Web 2 package to be installed along with Icinga 2, then you could add it to the `icinga2_packages` variable in your playbook (note that I haven't tested this):

```yaml
icinga2_packages:
  - icinga2
  - icingaweb2
```

However if you're looking for a role to install **and** configure Icinga Web 2 (e.g. create a database and add an Icinga 2 API user etc.) then a new role would be needed. This is something we may look at developing in the future but I'm afraid I can't promise anything.

**Comment by atj** [comment]
I'm closing this issue but if you have any further questions then let me know.
